### ISSUE TITLE
There are some race conditions while updating the node's information

### ISSUE THREAD

**Issue by jollaman999** [hcloud-classic/hcc-flute#1]
There are some race conditions in ipmiCheck go routines.
The issue is exist in this file.
`lib/ipmi/ipmiCheck.go`

I think we should check if go routine is locked before re-run to prevent race conditions.

**Comment by hcloudclassic** [comment]
@jollaman999 
Thank you for your advice.
The issue is fixed in https://github.com/hcloud-classic/hcc-flute/commit/9d9071f0277745bd8db30989cf7fc25d64aa7082.
