### ISSUE TITLE
Node's power state is not changed sometimes

### ISSUE THREAD

**Issue by ish-hcc** [hcloud-classic/hcc-flute#3]
Node's power state is not changed even I turned off the node completely.
It seems there is a issue with node update logic.

**Comment by jollaman999** [comment]
It looks there is a issue with go routine in ipmiChecker.

**Comment by ish-hcc** [comment]
Fixed in https://github.com/hcloud-classic/hcc-flute/commit/bd38271338c5e969f6d71f72fc60ecc7fea12b9d

**Comment by hcloudclassic** [comment]
Nice work.
